name: Image Clustering 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pip install pytest
        pytest tests/test_image_clus.py
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src
      continue-on-error: true
    - name: Run bandit
      run: |
        pip install bandit
        bandit -r -lll src;

